// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeBotDiscord.Data;

#nullable disable

namespace PokeBotDiscord.Migrations
{
    [DbContext(typeof(PokeBotDbContext))]
    [Migration("20251127202936_AddTutorialTables")]
    partial class AddTutorialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<int>("MoveBattleEventChancePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveBattleWinMaxMoneyReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveBattleWinMinMoneyReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveItemEventChancePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaminaPerHour")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadgeCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.InventoryItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hidden")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequiredGymId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FromLocationId");

                    b.HasIndex("RequiredGymId");

                    b.HasIndex("ToLocationId");

                    b.ToTable("LocationConnections");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreTypeId");

                    b.HasIndex("LocationId", "StoreTypeId")
                        .IsUnique();

                    b.ToTable("LocationStores");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccessToGym")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccessToPokemonCenter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccessToPokemonLeague")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AccessToShop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GymId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWildEncounters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("LocationTypes");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.MoveRandomItemReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("MoveRandomItemRewards");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStamina")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastTurnAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("GuildId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PlayerGymBadge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GymId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ObtainedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.HasIndex("PlayerId", "GymId")
                        .IsUnique();

                    b.ToTable("PlayerGymBadges");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PlayerTutorialMissionProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TutorialMissionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TutorialMissionId");

                    b.HasIndex("PlayerId", "TutorialMissionId")
                        .IsUnique();

                    b.ToTable("PlayerTutorialMissionProgresses");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PlayerTutorialStepProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RewardClaimed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RewardClaimedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TutorialStepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TutorialStepId");

                    b.HasIndex("PlayerId", "TutorialStepId")
                        .IsUnique();

                    b.ToTable("PlayerTutorialStepProgresses");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonEncounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinLevel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("PokemonEncounters");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InParty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonSpeciesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("PokemonSpeciesId");

                    b.ToTable("PokemonInstances");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonRarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxMoneyReward")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinMoneyReward")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PokemonRarities");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonRarityCatchRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BallCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CatchRatePercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PokemonRarityId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PokemonRarityId", "BallCode")
                        .IsUnique();

                    b.ToTable("PokemonRarityCatchRates");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PokemonRarityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpriteUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PokemonRarityId");

                    b.ToTable("PokemonSpecies");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.StoreType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoreTypes");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.StoreTypeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("StoreTypeId", "ItemTypeId")
                        .IsUnique();

                    b.ToTable("StoreTypeItems");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.TutorialMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConditionCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TutorialStepId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TutorialStepId");

                    b.ToTable("TutorialMissions");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.TutorialStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardItemQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RewardItemTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardMoney")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TitleKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RewardItemTypeId");

                    b.ToTable("TutorialSteps");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.InventoryItem", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.Player", "Owner")
                        .WithMany("Inventory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.Location", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.LocationType", "LocationType")
                        .WithMany("Locations")
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationConnection", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.Gym", "RequiredGym")
                        .WithMany()
                        .HasForeignKey("RequiredGymId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PokeBotDiscord.Data.Entities.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromLocation");

                    b.Navigation("RequiredGym");

                    b.Navigation("ToLocation");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationStore", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.StoreType", "StoreType")
                        .WithMany("LocationStores")
                        .HasForeignKey("StoreTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("StoreType");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationType", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Gym");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.MoveRandomItemReward", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.Player", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PlayerGymBadge", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.Player", "Player")
                        .WithMany("GymBadges")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gym");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PlayerTutorialMissionProgress", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.TutorialMission", "TutorialMission")
                        .WithMany("PlayerProgress")
                        .HasForeignKey("TutorialMissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TutorialMission");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PlayerTutorialStepProgress", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.TutorialStep", "TutorialStep")
                        .WithMany("PlayerProgress")
                        .HasForeignKey("TutorialStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("TutorialStep");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonEncounter", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.PokemonSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonInstance", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.Player", "Owner")
                        .WithMany("Party")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.PokemonSpecies", "Species")
                        .WithMany()
                        .HasForeignKey("PokemonSpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonRarityCatchRate", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.PokemonRarity", "PokemonRarity")
                        .WithMany("CatchRates")
                        .HasForeignKey("PokemonRarityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonRarity");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonSpecies", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.PokemonRarity", "Rarity")
                        .WithMany("Species")
                        .HasForeignKey("PokemonRarityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.StoreTypeItem", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokeBotDiscord.Data.Entities.StoreType", "StoreType")
                        .WithMany("Items")
                        .HasForeignKey("StoreTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemType");

                    b.Navigation("StoreType");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.TutorialMission", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.TutorialStep", "TutorialStep")
                        .WithMany("Missions")
                        .HasForeignKey("TutorialStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TutorialStep");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.TutorialStep", b =>
                {
                    b.HasOne("PokeBotDiscord.Data.Entities.ItemType", "RewardItemType")
                        .WithMany()
                        .HasForeignKey("RewardItemTypeId");

                    b.Navigation("RewardItemType");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.LocationType", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.Player", b =>
                {
                    b.Navigation("GymBadges");

                    b.Navigation("Inventory");

                    b.Navigation("Party");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.PokemonRarity", b =>
                {
                    b.Navigation("CatchRates");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.StoreType", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("LocationStores");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.TutorialMission", b =>
                {
                    b.Navigation("PlayerProgress");
                });

            modelBuilder.Entity("PokeBotDiscord.Data.Entities.TutorialStep", b =>
                {
                    b.Navigation("Missions");

                    b.Navigation("PlayerProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
